### ISSUE TITLE
MSM needs hwinfo

### ISSUE THREAD

**Issue by Strit** [manjaro-arm/packages-extra#1]
Manjaro settings manager needs [hwinfo](https://www.archlinux.org/packages/community/x86_64/hwinfo/) which in turn needs [libx86emu](https://www.archlinux.org/packages/community/x86_64/libx86emu/) and non of them are in Arch Linux ARM's packages.

We should "fork" the Arch Linux/Manjaro packages, and edit them to build on ARM.

**Comment by dodgejcr** [comment]
Agreed, I had it in extra at one point and it stopped building with the simple modifications that were required initially. I will eventually add it back.

**Comment by Strit** [comment]
I added hwinfo and libx86emu to the repo. I added the arm architectures, I just haven't had time to test build them yet.

I only know they build on my x86_64 laptop.

**Comment by dodgejcr** [comment]
I will test them when I get out of class. I have a shell that I know compiles that I was working on a few days ago but havent added just yet. I will test yours as well since they are already in there.

**Comment by Strit** [comment]
Cool. Let me know how they turn out.
If they work, I can add them to the build server.

**Comment by dodgejcr** [comment]
They work, for some reason -mtune-generic is a part of the makepkg config so I also updated the pacman package to remove that (not really needed). After that is removed, the builds are fine.

Closing issue.

**Comment by Strit** [comment]
Cool. I'll add them to buil server later today.
