### ISSUE TITLE
[kodi-rbp] is it really needed?

### ISSUE THREAD

**Issue by Strit** [manjaro-arm/packages-extra#2]
Is the kodi-rbp package really needed in Manjaro-ARM?
It's in the ALARM repo's, and as far as I can see in the PKGBUILD, there are no manjaro specific patches.
If it's not needed, it should be removed from this repo.

**Comment by dodgejcr** [comment]
I added it there in case we need to make any altercations. Right now, yeah its the same as the kodi-rbp package. It can be ignored on any build scripts

EDIT: I just went ahead and removed it. Best to not have anything in there that could be confusing

**Comment by Strit** [comment]
Yep, al right.
