### ISSUE TITLE
[manjaro-meta] PKGBUILD incomplete

### ISSUE THREAD

**Issue by Strit** [manjaro-arm/packages-extra#3]
The PKGBUILD for manjaro-meta seems incomplete.
It has a lot or ARCH stuff for i686 and x86_64 but nothing for ARM, except the arch pkgbuild line at the top.

This should be fixed and tested before added to repo.

Again, is this package actually needed on ARM at all?

**Comment by dodgejcr** [comment]
This package is currently not needed. I kept it in the repo as this is a great way to include meta packages that will be Manjaro specific in the future. There is a chance we can use the printer specific parts of this but currently we can remove it or at least remove it from any build scripts

**Comment by Strit** [comment]
Okay. I'll just neglect to add it to build server.
