### ISSUE TITLE
[pamac] gtk error when building

### ISSUE THREAD

**Issue by Strit** [manjaro-arm/packages-extra#5]
This is the error:

> valac  -o pamac-tray \
>       -X -w --pkg=posix -X -DGETTEXT_PACKAGE="pamac" --target-glib=2.38 \
>       --pkg=gtk+-3.0 \
>       --pkg=libnotify \
>       common.vala pamac_config.vala \
>       tray.vala
> pamac_config.vala:128.3-128.19: warning: method `Pamac.Config.write' never used
>       public void write (HashTable<string,Variant> new_conf) {
>       ^^^^^^^^^^^^^^^^^
> /var/lib/jenkins/workspace/pamac/manjaro-arm/armv7/pamac/src/pamac-4.1.0/src/tray.vala.c:30:21: >fatal error: gtk/gtk.h: No such file or directory
> # include <gtk/gtk.h>
> 
> ```
>                ^
> ```
> 
> compilation terminated.
> error: cc exited with status 256

Both gtk2 and gtk3 is installed.

**Comment by Strit** [comment]
My x86_64 laptop, does not have this issue. :(

**Comment by Strit** [comment]
According to the diff in https://github.com/manjaro-arm/packages-extra/commit/717e1231ec489b7656fd7e69a237d7ad34baecc0 the only change to pamac was the removal of the pamac.install script. Which only contained a message anyway.

So I have no idea why this commit fails to build, when the previous one worked.

**Comment by dodgejcr** [comment]
Hrm, not got much time but it did build on the x86 machine I have on me. 

I did update it a bit up to upstream from manjaro. https://github.com/manjaro-arm/packages-extra/issues

I assume something there went bad so when I get home I will look through on the merge and see if I can find out what I broke.

**Comment by dodgejcr** [comment]
Alright, been playing with this for a while now. Its looking for a gtk/gtk.h file. From the Makefile, it should be in the include dir (/usr/include) however it doesn't exist. I've installed just about every gtk component that I can find, symlinked gtk-2 to gtk and gtk-3 to gtk still with same error. Im not sure how you have got it to build but I must be missing someting on my end.

**Comment by Strit** [comment]
mhwd provides libegl, but not the egl.pc file needed by gtk to compile Pamac. Uninstalling mhwd and installed mesa and mesa-libgl works.
